package com.gadget69.catalog.config;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class LegacySchemaRepairTest {

  private JdbcTemplate jdbcTemplate;
  private LegacySchemaRepair legacySchemaRepair;

  @BeforeEach
  void setUp() {
    DriverManagerDataSource dataSource = new DriverManagerDataSource();
    dataSource.setDriverClassName("org.h2.Driver");
    dataSource.setUrl("jdbc:h2:mem:legacy-schema-repair;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
    dataSource.setUsername("sa");
    dataSource.setPassword("");

    jdbcTemplate = new JdbcTemplate(dataSource);
    legacySchemaRepair = new LegacySchemaRepair(jdbcTemplate);

    jdbcTemplate.execute("DROP TABLE IF EXISTS customer_orders");
    jdbcTemplate.execute("""
        CREATE TABLE customer_orders (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          customer_name VARCHAR(255) NOT NULL,
          phone VARCHAR(255) NOT NULL,
          address VARCHAR(3000) NOT NULL,
          pincode VARCHAR(255) NOT NULL,
          total_amount NUMERIC(12, 2) NOT NULL,
          payment_status VARCHAR(255) NOT NULL,
          razorpay_order_id VARCHAR(255),
          razorpay_payment_id VARCHAR(255),
          created_at TIMESTAMP NOT NULL
        )
        """);
    jdbcTemplate.update("""
        INSERT INTO customer_orders (
          customer_name, phone, address, pincode, total_amount, payment_status, razorpay_order_id,
          razorpay_payment_id, created_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
        """,
        "Legacy Customer", "9876543210", "42 Market Street", "600001", 1499.00, "PENDING", null, null);
  }

  @Test
  void addsMissingCheckoutColumnsAndBackfillsCurrency() {
    legacySchemaRepair.repairLegacySchemas();

    List<String> columns = jdbcTemplate.queryForList("""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = 'CUSTOMER_ORDERS'
        """, String.class);

    assertTrue(columns.contains("CURRENCY"));
    assertTrue(columns.contains("AMOUNT_PAISE"));
    assertTrue(columns.contains("CUSTOMER_PHONE"));
    assertTrue(columns.contains("ORDER_STATUS"));
    assertTrue(columns.contains("UPDATED_AT"));
    assertTrue(columns.contains("IS_DELETED"));
    assertTrue(columns.contains("RAZORPAY_SIGNATURE"));
    assertTrue(columns.contains("LAST_RAZORPAY_EVENT_ID"));
    assertEquals("INR", jdbcTemplate.queryForObject(
        "SELECT currency FROM customer_orders WHERE id = 1",
        String.class));
    assertEquals("9876543210", jdbcTemplate.queryForObject(
        "SELECT customer_phone FROM customer_orders WHERE id = 1",
        String.class));
    assertEquals("PENDING", jdbcTemplate.queryForObject(
        "SELECT order_status FROM customer_orders WHERE id = 1",
        String.class));
  }

  @Test
  void skipsLegacyPhoneBackfillWhenOnlyCustomerPhoneExists() {
    jdbcTemplate.execute("DROP TABLE IF EXISTS customer_orders");
    jdbcTemplate.execute("""
        CREATE TABLE customer_orders (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          customer_name VARCHAR(255) NOT NULL,
          customer_phone VARCHAR(255) NOT NULL,
          address VARCHAR(3000) NOT NULL,
          pincode VARCHAR(255) NOT NULL,
          total_amount NUMERIC(12, 2) NOT NULL,
          payment_status VARCHAR(255) NOT NULL,
          order_status VARCHAR(255) NOT NULL,
          created_at TIMESTAMP NOT NULL,
          updated_at TIMESTAMP NOT NULL,
          is_deleted BOOLEAN NOT NULL
        )
        """);
    jdbcTemplate.update("""
        INSERT INTO customer_orders (
          customer_name, customer_phone, address, pincode, total_amount, payment_status,
          order_status, created_at, updated_at, is_deleted
        ) VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE)
        """,
        "Modern Customer", "9999988888", "18 Lake View", "560001", 1499.00, "PENDING", "PENDING");

    legacySchemaRepair.repairLegacySchemas();

    assertEquals("9999988888", jdbcTemplate.queryForObject(
        "SELECT customer_phone FROM customer_orders WHERE id = 1",
        String.class));
  }
}
